### PR TITLE
Add append function to array to insert multiple values.

### PR DESCRIPTION
**Pull request by MeirShpilraien**
The new API allows to push multiple values to an array. I believe it will be more efficient than insert them one by one using the insert function as it will perform shift only once (which is probably implemented more efficient).
Let me know what you think, thanks.

### CODE REVIEW

**Comment by Diggsey** [comment]
Hi @MeirShpilraien, thanks for the PR. However, I think `append` is the wrong name for this method. I'd also rather not add methods that do not already exist on `Vec`.

The closest method would be `Vec::splice` - if you want to refactor this PR to implement the same method for `IArray` then I would be happy to accept that. However, please take care to avoid introducing UB - calling user-provided methods such as those on the Iterator or Into traits whilst in an `unsafe` block can be dangerous, so look to the `libstd` implementations for reference.

**Comment by MeirShpilraien** [comment]
Thanks @Diggsey , maybe I am missing something (new to rust), but isn't append exists for `Vec` (https://doc.rust-lang.org/std/vec/struct.Vec.html#method.append)? The difference is that it takes another `Vec` and leave it empty, is this what you meant? that we are not compatible to `Vec`? 

Good point about the unsafe comment, will fix that (though I thought unsafe is compile time only so not sure if it will effect the user? will it?)

**Comment by Diggsey** [comment]
Yes, having a method with the same name that does something different would be even worse than having a method that doesn't exist on Vec at all 😛 

> Good point about the unsafe comment, will fix that (though I thought unsafe is compile time only so not sure if it will effect the user? will it?)

It's not that there *was* UB, but if you call into user-code you have to be aware that it might panic (which if called from unsafe could result in broken safety invariants) or might observe the invariants that are temporarily broken by the unsafe code.

**Comment by MeirShpilraien** [comment]
You are right, I was intended to implement `splice` and mistakenly call it `append`. I will fix that and will also fix your comment about unsafe. Thanks for your help and feedback.

**Comment by Diggsey** [comment]
Closing due to inactivity. Feel free to re-open.

**Pull request closed without merging**
